# 服务端口
server:
  port: 8002

# 服务名
spring:
  application:
    name: service-oss
  # 环境设置: dev - test - prod
  profiles:
    active: dev

# 阿里云OSS
aliyun:
  oss:
    file:
      # 地域节点
      endpoint: oss-cn-shenzhen.aliyuncs.com
      # accesskey id
      keyid: LTAI4G4KtaC91AcFYwnppGjR
      # accesskey secret
      keysecret: o8MRah0AfcQBx0Kk3ykKNfM4gEuoYZ
      # bucket名
      bucketname: iam-online-edu